# Generated by Django 4.1.4 on 2022-12-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_auto_20221217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='resteurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='homeApp.resteurantmodal'),
        ),
    ]
