# Generated by Django 4.1.4 on 2022-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_alter_productmodel_resteurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
