# Generated by Django 4.1.4 on 2022-12-18 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_menucategorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCategoryModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='menuCategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
