# Generated by Django 4.1.4 on 2022-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApp', '0002_alter_orderitemmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
