# Generated by Django 4.1.4 on 2022-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApp', '0003_ordermodel_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='note',
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
