# Generated by Django 4.1.4 on 2022-12-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_delete_menucategorymodel_productmodel_menucategory'),
        ('ordersApp', '0004_remove_ordermodel_note_orderitemmodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='resteurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resteurant', to='homeApp.resteurantmodal'),
        ),
    ]
