# Generated by Django 4.1.4 on 2022-12-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_delete_menucategorymodel_productmodel_menucategory'),
        ('ordersApp', '0005_alter_ordermodel_resteurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='resteurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resteurant', to='homeApp.resteurantmodal'),
            preserve_default=False,
        ),
    ]
