# Generated by Django 4.1.4 on 2022-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('postCode', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
