# Generated by Django 4.1.4 on 2022-12-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeApp', '0007_delete_menucategorymodel_productmodel_menucategory'),
        ('accountApp', '0004_favoriteresteurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteResteurantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=True)),
                ('resteurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resteurants', to='homeApp.resteurantmodal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteResteurants',
        ),
    ]
