# Generated by Django 4.1.4 on 2022-12-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phoneNr',
            field=models.CharField(max_length=15),
        ),
    ]
